language: python
python: 2.7
env:
  global:
  - TEST_ENV=Travis-CI
  - secure: s5DrnETpuQfrDk24B9HSJh27PAziMUStFxQQP8tNnGvVSZc2/KjrrxfIXf8+/PaI0pE1UIsRW218oZvuJc4pWyMg6l+FI+Kie/GSlnl28a2SeXonskGkX4PIsf1eAEWgETuwwnyY8qAV8ghz/P5Q2BlQGS9wNqv00L3zAd1utV4=
  - secure: HoEzSlA7VX+ANJJyNBbexotMWYyL2o5yDV3wRq5EdWIKm1g+XBTduhT9yDCv2/pyTRsBSSVq4SiIxwiyt8DVAajZQ3EIoAIpMGC6EUMpucfabxIhj8duW/7tt8+8MyCii0B1Wc6HSHi3LsXAvUSd/LF8u2VYafbNQrcxAD3rYgw=
  - secure: Oihhvk59MkpxC9YedtlpQ3oczNbA1KDvF8tW0Ny5ZLyvJ4CThw7ORs5FarA3DIXJclF2CO78s049v2/R3Ege0N3DZro5aIuEIxhisQbwQF24s9ZE9A+4NWHUn/Re3+oy7MS2dC+X2tohpB1LBkxK2+epI+5h+6aDDVWtFQQ5rzg=
  - secure: E9IRnePrOmxLZDDU06cHyaJm/uiWdzeXESMbqv1fAS16GeaXAhRb5BlAHKmPdnwQqLRkzTH5nD66RwiWyGq3RnjPfSoX26ym/SY/nz9AQtrp3jyQ20hBkv+ZNDxJlabQgD6qAewy8qLEvL1byh5Ea31FoIuiCheLh1qzkW1CBLI=
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=pep257
  - TOX_ENV=docs
  - TOX_ENV=flake8
install:
- pip install tox
script:
- tox -e $TOX_ENV
after_success:
- coveralls
